B4A=true
Group=Default Group
ModulesStructureVersion=1
Type=Class
Version=9.85
@EndOfDesignText@
' ##########################################
' Example Project TDextended nativ View Collection
' ------------------------------------------
' Name:		TDextViewCollection
' Version:	1
' libs:		Audio,IME
' Designer: Yes
' ------------------------------------------
' (C) TechDoc G. Becker
' ##########################################
#Region Shared Files
#CustomBuildAction: folders ready, %WINDIR%\System32\Robocopy.exe,"..\..\Shared Files" "..\Files"
'Ctrl + click to sync files: ide://run?file=%WINDIR%\System32\Robocopy.exe&args=..\..\Shared+Files&args=..\Files&FilesSync=True
#End Region

'Ctrl + click to export as zip: ide://run?File=%B4X%\Zipper.jar&Args=Project.zip

#region Readme
	' ##### extended Views
	' EditText 		-> TDextEditText
	' RadioButton	-> TDextRadioButton
	' CheckBox		-> TDExtCheckBox
	' ImagView		-> next update
	' ListView		-> next update
	' Spinner		-> next update
	' Progressbar	-> next update
	
	' ##### Views Properties get/set by code
	' ##### other Custom Properties set by Designer
	
	' ##### TDextEditText ##################
	' TDextEditText1.BorderColor =		set border color
	' TDextEditText1.InputChars =		set only allowed chars for the keyboard
	' TDextEditText1.Spellcheck = 		set Spellchecking on/of (True(False)
	' TDextEditText1.Text =				set Text
	' TDextEditText1.TextColor =		set Textcolor
	' TDextEditText1.TextSize =			set Textsize
	
	' TDextEditText1.BringToFront		bring view to front
	' TDextEditText1.EditTextView		get view internal EditTextView
	' TDextEditText1.GetFocus			set Focus to view
	
	' X = TDextEditText1.ViewID			get unique ViewID (String)
	' x = TDextEditText1.ColumnName		get Databaound ColumnName
	' x = TDextEditText1.ColumnType		get Datatbound ColumnTye
	' x = TDextEditText1.EditTextView	get the EditTextView Object
	
	' ##### Views Custom Properties DesignerView
	' All Text Properties of the native EditTextView
	' ViewID: Custom uniqe ID to identify the view
	' Spell Check: switch it on/off
	' Column Name: Name of the databound Tablecolumn
	' Column Typ: Type of the databound Tablecolumn
	' Input Max Length
	' Input Min Length
	' Input Chars: enabled chars/keys on the keyboard
	' Background Focus Color: background color if has focus
	' Text Error Color: color if Date/Time check fails
	' Background Error Color: color if Date/Time check fails
	' Error Beep: error signal if Date/Time or input length check fails
	' Border Focus: view has a border if focused if not next properties values are used
	' Border Color
	' Border Width
	' Border Radius

	' ##### TDextRadioButton ##################
	' TDextRadioButton.Text =		set Text
	' TDextRadioButton.TextColor =	set Textcolor
	' TDextRadioButton.TextSize =	set Textsize
	' TDextRadioButton.Checked = 	true/false
	' X = TDextRadioButton.RadioButton 	get the internal RadioButton Object
	' X = TDextRadioButton.Value	get current value
	' TDextRadioButton.value = 	set Value/checked
	
	' ViewID: Custom uniqe ID to identify the view
	' Column Name: Name of the databound Tablecolumn
	' Column Typ: Type of the databound Tablecolumn
	' Value: checked=1, not checked=0
	
	' ##### TDextCheckBox ##################
	' TDextCheckBox.Text =		set Text
	' TDextCheckBox.TextColor =	set Textcolor
	' TDextCheckBox.TextSize =	set Textsize
	' TDextCheckBox.Checked = 	true/false
	' X = TDextCheckBox.RadioButton 	get the internal RadioButton Object
	' X = TDextCheckBox1.Value	get current value
	' TDextCheckBox1.value = 	set Value/checked
	
	' ViewID: Custom uniqe ID to identify the view
	' Column Name: Name of the databound Tablecolumn
	' Column Typ: Type of the databound Tablecolumn
	' Value: checked=1, not checked=0
	
	' ##### to be done ##################
	
#end region
	
Sub Class_Globals
	Private Root As B4XView
	Private xui As XUI
	' The Custom View generated by the Desinger
	Private TDextEditText1 As TDextEditText
	Private TDextRadioButton1 As TDextRadioButton
	Private TDextCheckBox1 As TDextCheckBox
End Sub

Public Sub Initialize
'	B4XPages.GetManager.LogEvents = True
End Sub

Private Sub B4XPage_Created (Root1 As B4XView)
	Root = Root1
	Root.LoadLayout("MainPage")
	
	
End Sub

#region TDextEditText
'###### Native TextChanged Event
'###### InputLength Check is done by the view
'checked
Private Sub TDextEditText1_TextChanged(Old As String, New As String)
	ToastMessageShow("Text changed",False)
End Sub

'###### Enhanced FocusChanged Event
'###### If leave and Column Type = Date/Time/DateTime the input is
'###### checked for correct format
'checked
Private Sub TDextEditText1_FocusChanged(HasFocus As Boolean,Error As Int)
	ToastMessageShow("Focus changed",False)
	If Error <> 0 Then showError(Error)
End Sub

'###### Enhanced EnterPressed Event
'###### If pressed and Column Type = Date/Time/DateTime the input is
'###### checked for correct format
'checked
Private Sub TDextEditText1_EnterPressed(Error As Int)
	ToastMessageShow("Enter Pressed",False)
	If Error <> 0 Then showError(Error)
End Sub

'###### Example to show Errors from FocusChanged and EnterPressed Events
'###### -1: Dateformat wrong
'###### -2: Timeformat wrong
'###### -3: Date/Time format wrong
'###### 0: OK
private Sub showError(Err As Int)
	Dim msg As String
	Select Case Err
		Case -1
			msg = "Wrong Date Format!"
		Case -2
			msg = "WrongTime Format!"
		Case -3
			msg = "Wrong Date/Time Format!"
	End Select
	xui.MsgboxAsync(msg,"Input Error!")
End Sub
#end region

#region TDextRadioButton
'##### checked
Private Sub TDextRadioButton1_CheckedChanged(Checked As Boolean, Value As Int)
	xui.Msgboxasync("Value: " & Value,"TDExtRadioButton")
End Sub
#end region

#region TDextCheckBox1_CheckedChanged
' checked
Private Sub TDextCheckBox1_CheckedChanged(Checked As Boolean, Value As Int)
	xui.Msgboxasync("Value: " & Value,"TDExtRadioButton")
End Sub
#end region