#import "iCore.h"
#import "iXUI.h"
@class _treetype;
@interface b4i_b4xtree : B4IClass
{
@public B4IList* __tree;
@public int __stextcolor;
@public int __btextcolor;
@public int __ltextcolor;
@public int __size;
@public int __size2;
@public int __text_size;
@public int __infotext_size;
@public BOOL __onebranch;
@public BOOL __borderline;
@public NSString* __meventname;
@public NSObject* __mcallback;
@public B4XViewWrapper* __mbase;
@public B4IXUI* __xui;
@public B4XViewWrapper* __scroll;
@public B4XViewWrapper* __panel;
@public B4IScrollView* __sc;
@public int __toph;
@public int __timelapse;
@public int __badgetextcolor;
@public int __badgebackgroundcolor;
@public int __badgetextsize;
@public int __badgedept;

}- (NSString*)  _add:(NSString*) _name :(NSString*) _idbranch :(NSString*) _fontawesonesymbol :(int) _color :(B4IArray*) _listleaf;
- (NSString*)  _add2:(NSString*) _name :(NSString*) _idbranch :(NSString*) _symbol :(B4XFont*) _fontsymbol :(int) _color :(B4IArray*) _listleaf;
- (NSString*)  _addbadge:(NSObject*) _tag :(NSString*) _text :(B4XViewWrapper*) _basepanel :(NSString*) _labelbadged :(int) _badgeleft :(int) _badgetop;
- (NSString*)  _addbranch:(NSString*) _name :(NSString*) _idbranch :(NSString*) _idparent :(NSString*) _fontawesonesymbol :(int) _color;
- (NSString*)  _addbranch2:(NSString*) _name :(NSString*) _idbranch :(NSString*) _idparent :(NSString*) _symbol :(B4XFont*) _fontsymbol :(int) _color;
- (NSString*)  _addbranchdoublesymbol:(NSString*) _name :(NSString*) _idbranch :(NSString*) _idparent :(NSString*) _opensymbol :(NSString*) _closesymbol :(B4XFont*) _fontsymbol :(int) _color;
- (NSString*)  _adddoublesymbol:(NSString*) _name :(NSString*) _idbranch :(NSString*) _opensymbol :(NSString*) _closesymbol :(B4XFont*) _fontsymbol :(int) _color :(B4IArray*) _listleaf;
- (NSString*)  _addleaf:(NSString*) _name :(NSString*) _info :(NSString*) _idbleaf :(NSString*) _idparent;
- (NSString*)  _addleaf2:(NSString*) _name :(NSString*) _info :(NSString*) _note :(NSString*) _idbleaf :(NSString*) _idparent;
- (NSString*)  _addleaf3:(NSString*) _name :(NSString*) _info :(NSString*) _note :(B4XFont*) _fontnote :(int) _colornote :(NSString*) _idbleaf :(NSString*) _idparent :(NSString*) _fontawesonesymbol :(B4XFont*) _fontsymbol;
- (NSString*)  _addleaf3ontop:(NSString*) _name :(NSString*) _info :(NSString*) _note :(B4XFont*) _fontnote :(int) _colornote :(NSString*) _idbleaf :(NSString*) _idbranch :(NSString*) _fontawesonesymbol :(B4XFont*) _fontsymbol;
- (NSString*)  _addleafontop:(NSString*) _name :(NSString*) _info :(NSString*) _idleaf :(NSString*) _idbranch;
- (NSString*)  _addleafwithsymbol:(NSString*) _name :(NSString*) _info :(NSString*) _idbleaf :(NSString*) _idparent :(NSString*) _fontawesonesymbol :(B4XFont*) _fontsymbol;
- (NSString*)  _addleafwithsymbolontop:(NSString*) _name :(NSString*) _info :(NSString*) _idbleaf :(NSString*) _idbranch :(NSString*) _fontawesonesymbol :(B4XFont*) _fontsymbol;
- (NSString*)  _base_resize:(double) _width :(double) _height;
- (NSString*)  _class_globals;
@property (nonatomic)B4IList* _tree;
@property (nonatomic)int _stextcolor;
@property (nonatomic)int _btextcolor;
@property (nonatomic)int _ltextcolor;
@property (nonatomic)int _size;
@property (nonatomic)int _size2;
@property (nonatomic)int _text_size;
@property (nonatomic)int _infotext_size;
@property (nonatomic)BOOL _onebranch;
@property (nonatomic)BOOL _borderline;
@property (nonatomic)NSString* _meventname;
@property (nonatomic)NSObject* _mcallback;
@property (nonatomic)B4XViewWrapper* _mbase;
@property (nonatomic)B4IXUI* _xui;
@property (nonatomic)B4XViewWrapper* _scroll;
@property (nonatomic)B4XViewWrapper* _panel;
@property (nonatomic)B4IScrollView* _sc;
@property (nonatomic)int _toph;
@property (nonatomic)int _timelapse;
@property (nonatomic)int _badgetextcolor;
@property (nonatomic)int _badgebackgroundcolor;
@property (nonatomic)int _badgetextsize;
@property (nonatomic)int _badgedept;
- (NSString*)  _clear;
- (NSString*)  _collapsesallbranch;
- (NSString*)  _collapsesbranch:(NSString*) _idbranch;
- (NSString*)  _collapsesbranchandson:(NSString*) _idbranch;
- (B4XViewWrapper*)  _crealabel:(NSObject*) _tag :(NSString*) _text :(int) _textsz :(int) _textcolor :(int) _backgroundcolor;
- (B4XViewWrapper*)  _crealabel2:(NSObject*) _tag :(NSString*) _text :(B4XFont*) _afont :(int) _textcolor :(int) _backgroundcolor :(BOOL) _bordercolor;
- (B4XViewWrapper*)  _crealabelbold:(NSObject*) _tag :(NSString*) _text :(int) _textsz :(int) _textcolor :(int) _backgroundcolor;
- (B4XViewWrapper*)  _crealabelr:(NSObject*) _tag :(NSString*) _text :(B4XFont*) _afont :(int) _textcolor :(int) _backgroundcolor;
- (NSString*)  _createbranches:(NSString*) _idbranches :(int) _left;
- (NSString*)  _designercreateview:(NSObject*) _base :(B4ILabelWrapper*) _lbl :(B4IMap*) _props;
- (NSString*)  _expandallbranch;
- (NSString*)  _expandbranch:(NSString*) _idbranch;
- (NSString*)  _expandbranchandson:(NSString*) _idbranch;
- (NSString*)  _extraxtjs:(NSString*) _idbranches;
- (B4XViewWrapper*)  _getbase;
- (NSString*)  _getbranchname:(NSString*) _idbranch;
- (NSString*)  _getbranchofleaf:(NSString*) _idleaf;
- (int)  _getbranchtextcolor;
- (int)  _getheight;
- (int)  _getinfotextsize;
- (int)  _getitemheight;
- (BOOL)  _getleafbadgeactive:(NSString*) _idleaf;
- (NSString*)  _getleafbadgetext:(NSString*) _idleaf;
- (NSString*)  _getleafinfo:(NSString*) _idleaf;
- (NSString*)  _getleafname:(NSString*) _idleaf;
- (int)  _getleaftextcolor;
- (int)  _getleft;
- (BOOL)  _getonlycornercolor;
- (BOOL)  _getopenonlyonebranch;
- (int)  _gettextsize;
- (int)  _gettimeanimation;
- (int)  _gettop;
- (int)  _getwidth;
- (NSString*)  _initialize:(B4I*) _ba :(NSObject*) _callback :(NSString*) _eventname;
- (void)  _invalidate;
- (NSString*)  _label_click;
- (NSString*)  _label_longclick;
- (B4IList*)  _listofidbraches:(NSString*) _idbranche;
- (B4IList*)  _listofidleafs:(NSString*) _idbranche;
- (NSString*)  _moveleaf:(NSString*) _idleaf :(NSString*) _newidbranch;
- (NSString*)  _removebranch:(NSString*) _idbranch;
- (NSString*)  _removeleaf:(NSString*) _idleaf;
- (NSString*)  _setbranch:(NSString*) _idbranch :(NSString*) _newname;
- (NSString*)  _setbranchtextcolor:(int) _color;
- (NSString*)  _setheight:(int) _h;
- (NSString*)  _setinfotextsize:(int) _sz;
- (NSString*)  _setitemheight:(int) _height;
- (NSString*)  _setlayout:(int) _left :(int) _top :(int) _widh :(int) _height;
- (NSString*)  _setleaf:(NSString*) _idleaf :(NSString*) _newname :(NSString*) _newinfo;
- (NSString*)  _setleafbadge:(NSString*) _idleaf :(BOOL) _badgeactive :(NSString*) _badgetext;
- (NSString*)  _setleaftextcolor:(int) _color;
- (NSString*)  _setleft:(int) _l;
- (NSString*)  _setonlycornercolor:(BOOL) _b;
- (NSString*)  _setopenonlyonebranch:(BOOL) _b;
- (NSString*)  _settextsize:(int) _sz;
- (NSString*)  _settimeanimation:(int) _millisec;
- (NSString*)  _settop:(int) _t;
- (NSString*)  _setwidth:(int) _w;
- (NSString*)  _sort:(BOOL) _ascending;
- (NSString*)  _treetojson;
@end
@interface _treetype:NSObject
{
@public BOOL _IsInitialized;
@public NSString* _Name;
@public NSString* _Info;
@public NSString* _Note;
@public NSString* _ID;
@public NSString* _IDParent;
@public BOOL _Parent;
@public BOOL _Open;
@public NSString* _OpenAwesoneSymbol;
@public NSString* _CloseAwesoneSymbol;
@public B4XFont* _FontSymbol;
@public int _Color;
@public B4XFont* _FontNote;
@public int _ColorNote;
@public int _LastTop;
@public int _LastHeight;
@public BOOL _Badge;
@public NSString* _mBadge;
@public BOOL _Drawed;

}
@property (nonatomic)BOOL IsInitialized;
@property (nonatomic)NSString* Name;
@property (nonatomic)NSString* Info;
@property (nonatomic)NSString* Note;
@property (nonatomic)NSString* ID;
@property (nonatomic)NSString* IDParent;
@property (nonatomic)BOOL Parent;
@property (nonatomic)BOOL Open;
@property (nonatomic)NSString* OpenAwesoneSymbol;
@property (nonatomic)NSString* CloseAwesoneSymbol;
@property (nonatomic)B4XFont* FontSymbol;
@property (nonatomic)int Color;
@property (nonatomic)B4XFont* FontNote;
@property (nonatomic)int ColorNote;
@property (nonatomic)int LastTop;
@property (nonatomic)int LastHeight;
@property (nonatomic)BOOL Badge;
@property (nonatomic)NSString* mBadge;
@property (nonatomic)BOOL Drawed;
-(void)Initialize;
@end

