#import "iCore.h"
@interface b4i_panelscratchcard : B4IClass
{
@public NSString* __meventname;
@public NSObject* __mcallback;
@public B4IPanelWrapper* __pan;
@public B4IPanelWrapper* __scratchcard;
@public B4IWeakRef* __mmbase;
@public B4IPanelWrapper* __codebase;
@public B4ICanvas* __can;
@public float __lx;
@public float __ly;
@public int __thickness;
@public int __action_down;
@public int __action_up;
@public int __action_move;

}- (NSString*)  _addtoparent:(B4IPanelWrapper*) _parent :(int) _left :(int) _top :(int) _width :(int) _height;
- (NSString*)  _addview:(B4IViewWrapper*) _view :(int) _left :(int) _top :(int) _width :(int) _height;
- (NSString*)  _base_resize:(double) _width :(double) _height;
- (NSString*)  _bringtofront;
- (double)  _calcrelativekeyboardheight:(double) _keyboardheight;
- (NSString*)  _class_globals;
@property (nonatomic)NSString* _meventname;
@property (nonatomic)NSObject* _mcallback;
@property (nonatomic)B4IPanelWrapper* _pan;
@property (nonatomic)B4IPanelWrapper* _scratchcard;
@property (nonatomic)B4IWeakRef* _mmbase;
@property (nonatomic)B4IPanelWrapper* _codebase;
@property (nonatomic)B4ICanvas* _can;
@property (nonatomic)float _lx;
@property (nonatomic)float _ly;
@property (nonatomic)int _thickness;
@property (nonatomic)int _action_down;
@property (nonatomic)int _action_up;
@property (nonatomic)int _action_move;
- (NSString*)  _clear;
- (NSString*)  _designercreateview:(B4IPanelWrapper*) _base :(B4ILabelWrapper*) _lbl :(B4IMap*) _props;
- (float)  _getalfa;
- (int)  _getcolor;
- (double)  _getfillingpercentage;
- (int)  _getheight;
- (BOOL)  _getisfocused;
- (int)  _getleft;
- (B4IPanelWrapper*)  _getparent;
- (int)  _getpixelcolor:(B4IBitmap*) _bitm :(int) _x :(int) _y;
- (NSObject*)  _gettag;
- (int)  _gettintcolor;
- (int)  _gettop;
- (B4IViewWrapper*)  _getview:(int) _index;
- (BOOL)  _getvisible;
- (int)  _getwidth;
- (NSString*)  _initialize:(B4I*) _ba :(NSObject*) _callback :(NSString*) _eventname;
- (NSString*)  _loadlayout:(NSString*) _layoutfile;
- (B4IPanelWrapper*)  _mbase;
- (NSString*)  _pan_click;
- (NSString*)  _pan_longclick;
- (NSString*)  _pan_touch:(int) _action :(float) _x :(float) _y;
- (B4IPanelWrapper*)  _panel;
- (NSString*)  _removeallviews;
- (NSString*)  _removeviewfromparent;
- (NSString*)  _removiewat:(int) _index;
- (NSString*)  _requestfocus;
- (BOOL)  _resignfocus;
- (NSString*)  _scartch:(BOOL) _enabled;
- (NSString*)  _scratchcard_touch:(int) _action :(float) _x :(float) _y;
- (NSString*)  _sendtoback;
- (NSString*)  _setalfa:(float) _a;
- (NSString*)  _setcolor:(int) _c;
- (NSString*)  _setheight:(int) _l;
- (NSString*)  _setlayoutanimated:(int) _duration :(int) _left :(int) _top :(int) _width :(int) _height;
- (NSString*)  _setleft:(int) _l;
- (NSString*)  _setparallaxeffect:(int) _vertical :(int) _horizzontal;
- (NSString*)  _setshadow:(int) _color :(float) _offsetx :(float) _offsety :(float) _opacity :(BOOL) _staticrect;
- (NSString*)  _settag:(NSObject*) _o;
- (NSString*)  _settinticolor:(int) _t;
- (NSString*)  _settop:(int) _l;
- (NSString*)  _setvisible:(BOOL) _b;
- (NSString*)  _setwidth:(int) _l;
- (NSString*)  _sizetofit;
@end

