B4J=true
Group=Default Group
ModulesStructureVersion=1
Type=Class
Version=5.9
@EndOfDesignText@
'Class Module
Sub Class_Globals
	'Private fx As JFX ' Uncomment if required. For B4j only
	Private TJO As JavaObject

End Sub
'Initializes the object. You can add parameters to this method if needed.
Public Sub Initialize
	'This is an autogenerated constructor, there may not be a matching constructor in the class, you will then have to remove the next line of code
	TJO.InitializeStatic("javax.sound.midi.Soundbank")
End Sub

'Obtains a textual description of the sound bank, suitable for display.
Public Sub GetDescription As String
	Return TJO.RunMethod("getDescription",Null)
End Sub
'Obtains an Instrument from the given Patch.
Public Sub GetInstrument(TPatch As MidiPatch) As MidiInstrument
	Dim Wrapper As MidiInstrument
	Wrapper.Initialize
	Wrapper.SetObject(TJO.RunMethod("getInstrument",Array As Object(TPatch.GetObject)))
	Return Wrapper
End Sub
'Obtains a list of instruments contained in this sound bank.
Public Sub GetInstruments As MidiInstrument()
	Dim Temp() As Object = TJO.RunMethod("getInstruments",Null)
	Dim Wrapper(Temp.length) As MidiInstrument
	For i = 0 To Temp.Length
		Wrapper(i).Initialize
		Wrapper(i).SetObject(Temp(i))
	Next
	Return Wrapper
End Sub
'Obtains the name of the sound bank.
Public Sub GetName As String
	Return TJO.RunMethod("getName",Null)
End Sub
'Extracts a list of non-Instrument resources contained in the sound bank.
Public Sub GetResources As JavaObject
	Return TJO.RunMethod("getResources",Null)
End Sub
'Obtains a string naming the company that provides the sound bank
Public Sub GetVendor As String
	Return TJO.RunMethod("getVendor",Null)
End Sub
'Obtains the version string for the sound bank.
Public Sub GetVersion As String
	Return TJO.RunMethod("getVersion",Null)
End Sub

'Get the unwrapped object
Public Sub GetObject As Object
	Return TJO
End Sub

'Get the unwrapped object As a JavaObject
Public Sub GetObjectJO As JavaObject
	Return TJO
End Sub
'Comment if not needed

'Set the underlying Object, must be of correct type
Public Sub SetObject(Obj As Object)
	TJO = Obj
End Sub


