B4J=true
Group=Default Group
ModulesStructureVersion=1
Type=Class
Version=8.8
@EndOfDesignText@
#IgnoreWarnings:12
'Class Module
Sub Class_Globals
	'Private fx As JFX ' Uncomment if required. For B4j only
	Private Tjo As JavaObject
End Sub
'Initializes the object. You can add parameters to this method if needed.
Public Sub Initialize
	'This is an autogenerated constructor, there may not be a matching constructor in the class, you will then have to remove the next line of code and use SetObject to wrap the object
	Tjo.InitializeStatic("org.dizitart.no2.NitriteContext")
End Sub

'Returns the wrapped object as JavaObject
Public Sub AsJavaObject As JavaObject
	Return Tjo
End Sub

Public Sub DropCollection(Name As String)
	Tjo.RunMethod("dropCollection",Array As Object(Name))
End Sub
'Gets the size of the auto-commit buffer.
Public Sub GetAutoCommitBufferSize As Int
	Return Tjo.RunMethod("getAutoCommitBufferSize",Null)
End Sub
'Gets the database file path.
Public Sub GetFilePath As String
	Return Tjo.RunMethod("getFilePath",Null)
End Sub
'Returns the wrapped object as Object
Public Sub GetObject As Object
	Return Tjo
End Sub
'Indicates if auto commit is enabled or not.
Public Sub IsAutoCommitEnabled As Boolean
	Return Tjo.RunMethod("isAutoCommitEnabled",Null)
End Sub
'Indicates if auto compact is enabled or not before close.
Public Sub IsAutoCompactEnabled As Boolean
	Return Tjo.RunMethod("isAutoCompactEnabled",Null)
End Sub
'Indicates if this is a compressed database or not.
Public Sub IsCompressed As Boolean
	Return Tjo.RunMethod("isCompressed",Null)
End Sub
'Indicates if this is an in-memory database or not.
Public Sub IsInMemory As Boolean
	Return Tjo.RunMethod("isInMemory",Null)
End Sub
'Indicates if this is a readonly database or not.
Public Sub IsReadOnly As Boolean
	Return Tjo.RunMethod("isReadOnly",Null)
End Sub

'Comment if not needed
'Set the underlying Object, must be of correct type
Public Sub SetObject(Obj As Object)
	Tjo = Obj
End Sub

