B4J=true
Group=Default Group
ModulesStructureVersion=1
Type=Class
Version=8.8
@EndOfDesignText@
#IgnoreWarnings:12
'Class Module
Sub Class_Globals
	'Private fx As JFX ' Uncomment if required. For B4j only
	Private Tjo As JavaObject
End Sub
'Initializes the object. You can add parameters to this method if needed.
Public Sub Initialize
	'This is an autogenerated constructor, there may not be a matching constructor in the class, you will then have to remove the next line of code and use SetObject to wrap the object
	Tjo.InitializeStatic("java.util.Iterator")
End Sub

'Returns the wrapped object as JavaObject
Public Sub AsJavaObject As JavaObject
	Return Tjo
End Sub
'Returns the wrapped object as Object
Public Sub GetObject As Object
	Return Tjo
End Sub
'Returns true if the iteration has more elements.
Public Sub HasNext As Boolean
	Return Tjo.RunMethod("hasNext",Null)
End Sub
'Returns the next element in the iteration.
Public Sub GetNext As Object
	Dim O As Object = Tjo.RunMethod("next",Null)
	Dim ElementType As String = GetType(O)
'	ElementType = ElementType.SubString(ElementType.LastIndexOf(".")+1)
	Select ElementType
		Case "org.dizitart.no2.Document"
			Dim DWrapper As NitriteDocument
			DWrapper.Initialize
			DWrapper.SetObject(O)
			Return DWrapper
		Case "org.dizitart.no2.NitriteId"
			Dim WWrapper As NitriteId
			WWrapper.Initialize
			WWrapper.SetObject(O)
			Return WWrapper
		Case Else
			Return O
	End Select
End Sub

'Comment if not needed
'Set the underlying Object, must be of correct type
Public Sub SetObject(Obj As Object)
	Tjo = Obj
End Sub

