B4J=true
Group=Default Group
ModulesStructureVersion=1
Type=Class
Version=9.8
@EndOfDesignText@
#IgnoreWarnings:12
'Class Module
Sub Class_Globals
	'Private fx As JFX ' Uncomment if required. For B4j only
	Private Tjo As JavaObject
End Sub
'Initializes the object. You can add parameters to this method if needed.
Public Sub Initialize
	'This is an autogenerated constructor, there may not be a matching constructor in the class, you will then have to remove the next line of code and use SetObject to wrap the object
	Tjo.InitializeStatic("java.awt.Graphics2D")
End Sub

'Sets the values of an arbitrary number of preferences for the rendering algorithms.
Public Sub AddRenderingHints(Hints As Map)
	Tjo.RunMethod("addRenderingHints",Array As Object(Hints))
End Sub
'Returns the wrapped object as JavaObject
Public Sub AsJavaObject As JavaObject
	Return Tjo
End Sub
'Intersects the current Clip with the interior of the specified Shape and sets the Clip to the resulting intersection.
Public Sub Clip(S As JavaObject)
	Tjo.RunMethod("clip",Array As Object(S))
End Sub
'Strokes the outline of a Shape using the settings of the current Graphics2D context.
Public Sub Draw(S As JavaObject)
	Tjo.RunMethod("draw",Array As Object(S))
End Sub
'Draws a 3-D highlighted outline of the specified rectangle.
Public Sub Draw3DRect(X As Int, Y As Int, Width As Int, Height As Int, Raised As Boolean)
	Tjo.RunMethod("draw3DRect",Array As Object(X, Y, Width, Height, Raised))
End Sub
'Draws a 3-D highlighted outline of the specified rectangle.
Public Sub Draw3DRect2(X As Int, Y As Int, Width As Int, Height As Int, Raised As Boolean)
	Tjo.RunMethod("draw3DRect",Array As Object(X, Y, Width, Height, Raised))
End Sub
'Renders the text of the specified GlyphVector using the Graphics2D context's rendering attributes.
Public Sub DrawGlyphVector(G As JavaObject, X As Float, Y As Float)
	Tjo.RunMethod("drawGlyphVector",Array As Object(G, X, Y))
End Sub
'Renders a BufferedImage that is filtered with a BufferedImageOp.
Public Sub DrawImage(Img As JavaObject, Op As Object, X As Int, Y As Int)
	Tjo.RunMethod("drawImage",Array As Object(Img, Op, X, Y))
End Sub
'Renders an image, applying a transform from image space into user space before drawing.
Public Sub DrawImage2(Img As JavaObject, Xform As Object, Obs As Object) As Boolean
	Return Tjo.RunMethod("drawImage",Array As Object(Img, Xform, Obs))
End Sub
'Renders a RenderableImage, applying a transform from image space into user space before drawing.
Public Sub DrawRenderableImage(Img As JavaObject, Xform As JavaObject)
	Tjo.RunMethod("drawRenderableImage",Array As Object(Img, Xform))
End Sub
'Renders a RenderedImage, applying a transform from image space into user space before drawing.
Public Sub DrawRenderedImage(Img As JavaObject, Xform As JavaObject)
	Tjo.RunMethod("drawRenderedImage",Array As Object(Img, Xform))
End Sub
'Draws the text given by the specified string, using this graphics context's current font and color.
Public Sub DrawString(Str As String, X As Float, Y As Float)
	Tjo.RunMethod("drawString",Array As Object(Str, X, Y))
End Sub
'Draws the text given by the specified string, using this graphics context's current font and color.
Public Sub DrawString2(Str As String, X As Int, Y As Int)
	Tjo.RunMethod("drawString",Array As Object(Str, X, Y))
End Sub
'Renders the text of the specified iterator applying its attributes in accordance with the specification of the TextAttribute class.
Public Sub DrawString3(Iterator As JavaObject, X As Float, Y As Float)
	Tjo.RunMethod("drawString",Array As Object(Iterator, X, Y))
End Sub
'Renders the text of the specified iterator applying its attributes in accordance with the specification of the TextAttribute class.
Public Sub DrawString4(Iterator As JavaObject, X As Int, Y As Int)
	Tjo.RunMethod("drawString",Array As Object(Iterator, X, Y))
End Sub

'Fills the interior of a Shape using the settings of the Graphics2D context.
Public Sub Fill(S As JavaObject)
	Tjo.RunMethod("fill",Array As Object(S))
End Sub
'Paints a 3-D highlighted rectangle filled with the current color.
Public Sub Fill3DRect(X As Int, Y As Int, Width As Int, Height As Int, Raised As Boolean)
	Tjo.RunMethod("fill3DRect",Array As Object(X, Y, Width, Height, Raised))
End Sub
'Paints a 3-D highlighted rectangle filled with the current color.
Public Sub Fill3DRect2(X As Int, Y As Int, Width As Int, Height As Int, Raised As Boolean)
	Tjo.RunMethod("fill3DRect",Array As Object(X, Y, Width, Height, Raised))
End Sub
'Returns the background color used for clearing a region.
Public Sub GetBackground As JavaObject
	Return Tjo.RunMethod("getBackground",Null)
End Sub
'Returns the current Composite in the Graphics2D context.
Public Sub GetComposite As JavaObject
	Return Tjo.RunMethod("getComposite",Null)
End Sub
'Returns the device configuration associated with this Graphics2D.
Public Sub GetDeviceConfiguration As JavaObject
	Return Tjo.RunMethod("getDeviceConfiguration",Null)
End Sub
'Get the rendering context of the Font within this Graphics2D context.
Public Sub GetFontRenderContext As JavaObject
	Return Tjo.RunMethod("getFontRenderContext",Null)
End Sub
'Returns the wrapped object as Object
Public Sub GetObject As Object
	Return Tjo
End Sub
'Returns the current Paint of the Graphics2D context.
Public Sub GetPaint As JavaObject
	Return Tjo.RunMethod("getPaint",Null)
End Sub
'Returns the value of a single preference for the rendering algorithms.
Public Sub GetRenderingHint(HintKey As JavaObject) As Object
	Return Tjo.RunMethod("getRenderingHint",Array As Object(HintKey))
End Sub
'Gets the preferences for the rendering algorithms.
Public Sub GetRenderingHints As JavaObject
	Return Tjo.RunMethod("getRenderingHints",Null)
End Sub
'Returns the current Stroke in the Graphics2D context.
Public Sub GetStroke As JavaObject
	Return Tjo.RunMethod("getStroke",Null)
End Sub
'Returns a copy of the current Transform in the Graphics2D context.
Public Sub GetTransform As JavaObject
	Return Tjo.RunMethod("getTransform",Null)
End Sub
'Checks whether or not the specified Shape intersects the specified Rectangle, which is in device space.
Public Sub Hit(Rect As JavaObject, S As JavaObject, OnStroke As Boolean) As Boolean
	Return Tjo.RunMethod("hit",Array As Object(Rect, S, OnStroke))
End Sub
'Concatenates the current Graphics2D Transform with a rotation transform.
Public Sub Rotate(Theta As Double)
	Tjo.RunMethod("rotate",Array As Object(Theta))
End Sub
'Concatenates the current Graphics2D Transform with a translated rotation transform.
Public Sub Rotate2(Theta As Double, X As Double, Y As Double)
	Tjo.RunMethod("rotate",Array As Object(Theta, X, Y))
End Sub
'Concatenates the current Graphics2D Transform with a scaling transformation Subsequent rendering is resized according to the specified scaling factors relative to the previous scaling.
Public Sub Scale(Sx As Double, Sy As Double)
	Tjo.RunMethod("scale",Array As Object(Sx, Sy))
End Sub
'Sets the background color for the Graphics2D context.
Public Sub SetBackground(Color As AWTColor)
	Tjo.RunMethod("setBackground",Array As Object(Color.GetObject))
End Sub
'Sets the Composite for the Graphics2D context.
Public Sub SetComposite(Comp As JavaObject)
	Tjo.RunMethod("setComposite",Array As Object(Comp))
End Sub
'Sets the Paint attribute for the Graphics2D context.
Public Sub SetPaint(TPaint As JavaObject)
	Tjo.RunMethod("setPaint",Array As Object(TPaint))
End Sub
'Sets the value of a single preference for the rendering algorithms.
Public Sub SetRenderingHint(HintKey As JavaObject, HintValue As Object)
	Tjo.RunMethod("setRenderingHint",Array As Object(HintKey, HintValue))
End Sub
'Replaces the values of all preferences for the rendering algorithms with the specified hints.
Public Sub SetRenderingHints(Hints As Map)
	Tjo.RunMethod("setRenderingHints",Array As Object(Hints))
End Sub
'Sets the Stroke for the Graphics2D context.
Public Sub SetStroke(S As JavaObject)
	Tjo.RunMethod("setStroke",Array As Object(S))
End Sub
'Overwrites the Transform in the Graphics2D context.
Public Sub SetTransform(Tx As JavaObject)
	Tjo.RunMethod("setTransform",Array As Object(Tx))
End Sub
'Concatenates the current Graphics2D Transform with a shearing transform.
Public Sub Shear(Shx As Double, Shy As Double)
	Tjo.RunMethod("shear",Array As Object(Shx, Shy))
End Sub
'Composes an AffineTransform object with the Transform in this Graphics2D according to the rule last-specified-first-applied.
Public Sub Transform(Tx As JavaObject)
	Tjo.RunMethod("transform",Array As Object(Tx))
End Sub
'Concatenates the current Graphics2D Transform with a translation transform.
Public Sub Translate(Tx As Double, Ty As Double)
	Tjo.RunMethod("translate",Array As Object(Tx, Ty))
End Sub
'Translates the origin of the Graphics2D context to the point (x, y) in the current coordinate system.
Public Sub Translate2(X As Int, Y As Int)
	Tjo.RunMethod("translate",Array As Object(X, Y))
End Sub
'Translates the origin of the graphics context to the point (x, y) in the current coordinate system.
Public Sub Translate3(X As Int, Y As Int)
	Tjo.RunMethod("translate",Array As Object(X, Y))
End Sub

'Comment if not needed
'Set the underlying Object, must be of correct type
Public Sub SetObject(Obj As Object)
	Tjo = Obj
End Sub

'Clears the specified rectangle by filling it with the background color of the current drawing surface.
Public Sub ClearRect(X As Int, Y As Int, Width As Int, Height As Int)
	Tjo.RunMethod("clearRect",Array As Object(X, Y, Width, Height))
End Sub
'Intersects the current clip with the specified rectangle.
Public Sub ClipRect(X As Int, Y As Int, Width As Int, Height As Int)
	Tjo.RunMethod("clipRect",Array As Object(X, Y, Width, Height))
End Sub
'Copies an area of the component by a distance specified by dx and dy.
Public Sub CopyArea(X As Int, Y As Int, Width As Int, Height As Int, Dx As Int, Dy As Int)
	Tjo.RunMethod("copyArea",Array As Object(X, Y, Width, Height, Dx, Dy))
End Sub
'Disposes of this graphics context and releases any system resources that it is using.
Public Sub Dispose
	Tjo.RunMethod("dispose",Null)
End Sub
'Draws a 3-D highlighted outline of the specified rectangle.

'Draws the outline of a circular or elliptical arc covering the specified rectangle.
Public Sub DrawArc(X As Int, Y As Int, Width As Int, Height As Int, StartAngle As Int, ArcAngle As Int)
	Tjo.RunMethod("drawArc",Array As Object(X, Y, Width, Height, StartAngle, ArcAngle))
End Sub
'Draws the text given by the specified byte array, using this graphics context's current font and color.
Public Sub DrawBytes(Data() As Byte, Offset As Int, Length As Int, X As Int, Y As Int)
	Tjo.RunMethod("drawBytes",Array As Object(Data, Offset, Length, X, Y))
End Sub
'Draws the text given by the specified character array, using this graphics context's current font and color.
Public Sub DrawChars(Data() As Char, Offset As Int, Length As Int, X As Int, Y As Int)
	Tjo.RunMethod("drawChars",Array As Object(Data, Offset, Length, X, Y))
End Sub
'Draws as much of the specified image as is currently available.
Public Sub DrawImage3(Img As Object, X As Int, Y As Int, Bgcolor As AWTColor, Observer As Object) As Boolean
	Return Tjo.RunMethod("drawImage",Array As Object(Img, X, Y, Bgcolor.GetObject, Observer))
End Sub
'Draws as much of the specified image as is currently available.
Public Sub DrawImage4(Img As JavaObject, X As Int, Y As Int, Observer As Object) As Boolean
	Return Tjo.RunMethod("drawImage",Array As Object(Img, X, Y, Observer))
End Sub
'Draws as much of the specified image as has already been scaled to fit inside the specified rectangle.
Public Sub DrawImage5(Img As JavaObject, X As Int, Y As Int, Width As Int, Height As Int, Bgcolor As AWTColor, Observer As Object) As Boolean
	Return Tjo.RunMethod("drawImage",Array As Object(Img, X, Y, Width, Height, Bgcolor.GetObject, Observer))
End Sub
'Draws as much of the specified image as has already been scaled to fit inside the specified rectangle.
Public Sub DrawImage6(Img As JavaObject, X As Int, Y As Int, Width As Int, Height As Int, Observer As Object) As Boolean
	Return Tjo.RunMethod("drawImage",Array As Object(Img, X, Y, Width, Height, Observer))
End Sub
'Draws a line, using the current color, between the points (x1, y1) and (x2, y2) in this graphics context's coordinate system.
Public Sub DrawLine(X1 As Int, Y1 As Int, X2 As Int, Y2 As Int)
	Tjo.RunMethod("drawLine",Array As Object(X1, Y1, X2, Y2))
End Sub
'Draws the outline of an oval.
Public Sub DrawOval(X As Int, Y As Int, Width As Int, Height As Int)
	Tjo.RunMethod("drawOval",Array As Object(X, Y, Width, Height))
End Sub
'Draws a closed polygon defined by arrays of x and y coordinates.
Public Sub DrawPolygon(XPoints() As Int, YPoints() As Int, NPoints As Int)
	Tjo.RunMethod("drawPolygon",Array As Object(XPoints, YPoints, NPoints))
End Sub
'Draws the outline of a polygon defined by the specified Polygon object.
Public Sub DrawPolygon2(P As JavaObject)
	Tjo.RunMethod("drawPolygon",Array As Object(P))
End Sub
'Draws a sequence of connected lines defined by arrays of x and y coordinates.
Public Sub DrawPolyline(XPoints() As Int, YPoints() As Int, NPoints As Int)
	Tjo.RunMethod("drawPolyline",Array As Object(XPoints, YPoints, NPoints))
End Sub
'Draws the outline of the specified rectangle.
Public Sub DrawRect(X As Int, Y As Int, Width As Int, Height As Int)
	Tjo.RunMethod("drawRect",Array As Object(X, Y, Width, Height))
End Sub
'Draws an outlined round-cornered rectangle using this graphics context's current color.
Public Sub DrawRoundRect(X As Int, Y As Int, Width As Int, Height As Int, ArcWidth As Int, ArcHeight As Int)
	Tjo.RunMethod("drawRoundRect",Array As Object(X, Y, Width, Height, ArcWidth, ArcHeight))
End Sub
'Fills a circular or elliptical arc covering the specified rectangle.
Public Sub FillArc(X As Int, Y As Int, Width As Int, Height As Int, StartAngle As Int, ArcAngle As Int)
	Tjo.RunMethod("fillArc",Array As Object(X, Y, Width, Height, StartAngle, ArcAngle))
End Sub
'Fills an oval bounded by the specified rectangle with the current color.
Public Sub FillOval(X As Int, Y As Int, Width As Int, Height As Int)
	Tjo.RunMethod("fillOval",Array As Object(X, Y, Width, Height))
End Sub
'Fills a closed polygon defined by arrays of x and y coordinates.
Public Sub FillPolygon(XPoints() As Int, YPoints() As Int, NPoints As Int)
	Tjo.RunMethod("fillPolygon",Array As Object(XPoints, YPoints, NPoints))
End Sub
'Fills the polygon defined by the specified Polygon object with the graphics context's current color.
Public Sub FillPolygon2(P As JavaObject)
	Tjo.RunMethod("fillPolygon",Array As Object(P))
End Sub
'Fills the specified rectangle.
Public Sub FillRect(X As Int, Y As Int, Width As Int, Height As Int)
	Tjo.RunMethod("fillRect",Array As Object(X, Y, Width, Height))
End Sub
'Fills the specified rounded corner rectangle with the current color.
Public Sub FillRoundRect(X As Int, Y As Int, Width As Int, Height As Int, ArcWidth As Int, ArcHeight As Int)
	Tjo.RunMethod("fillRoundRect",Array As Object(X, Y, Width, Height, ArcWidth, ArcHeight))
End Sub
'Deprecated.
'*
Public Sub Finalize
	Tjo.RunMethod("finalize",Null)
End Sub
'Gets the current clipping area.
Public Sub GetClip As JavaObject
	Return Tjo.RunMethod("getClip",Null)
End Sub
'Returns the bounding rectangle of the current clipping area.
Public Sub GetClipBounds As JavaObject
	Return Tjo.RunMethod("getClipBounds",Null)
End Sub
'Returns the bounding rectangle of the current clipping area.
Public Sub GetClipBounds2(R As JavaObject) As JavaObject
	Return Tjo.RunMethod("getClipBounds",Array As Object(R))
End Sub
'Deprecated.
'*
Public Sub GetClipRect As JavaObject
	Return Tjo.RunMethod("getClipRect",Null)
End Sub
'Gets this graphics context's current color.
Public Sub GetColor As JavaObject
	Return Tjo.RunMethod("getColor",Null)
End Sub
'Gets the current font.
Public Sub GetFont As AWTFont
	Dim Wrapper As AWTFont
	Wrapper.Initialize
	Wrapper.SetObject(Tjo.RunMethod("getFont",Null))
	Return Wrapper
End Sub
'Gets the font metrics of the current font.
Public Sub GetFontMetrics As JavaObject
	Return Tjo.RunMethod("getFontMetrics",Null)
End Sub
'Gets the font metrics for the specified font.
Public Sub GetFontMetrics2(F As JavaObject) As JavaObject
	Return Tjo.RunMethod("getFontMetrics",Array As Object(F))
End Sub
'Returns true if the specified rectangular area might intersect the current clipping area.
Public Sub HitClip(X As Int, Y As Int, Width As Int, Height As Int) As Boolean
	Return Tjo.RunMethod("hitClip",Array As Object(X, Y, Width, Height))
End Sub
'Sets the current clip to the rectangle specified by the given coordinates.
Public Sub SetClip(X As Int, Y As Int, Width As Int, Height As Int)
	Tjo.RunMethod("setClip",Array As Object(X, Y, Width, Height))
End Sub
'Sets the current clipping area to an arbitrary clip shape.
Public Sub SetClip2(tClip As JavaObject)
	Tjo.RunMethod("setClip",Array As Object(tClip))
End Sub
'Sets this graphics context's current color to the specified color.
Public Sub SetColor(C As AWTColor)
	Tjo.RunMethod("setColor",Array As Object(C.GetObject))
End Sub
'Sets this graphics context's font to the specified font.
Public Sub SetFont(TFont As AWTFont)
	Tjo.RunMethod("setFont",Array As Object(TFont.GetObject))
End Sub
'Sets the paint mode of this graphics context to overwrite the destination with this graphics context's current color.
Public Sub SetPaintMode
	Tjo.RunMethod("setPaintMode",Null)
End Sub
'Sets the paint mode of this graphics context to alternate between this graphics context's current color and the new specified color.
Public Sub SetXORMode(C1 As JavaObject)
	Tjo.RunMethod("setXORMode",Array As Object(C1))
End Sub
'Returns a String object representing this Graphics object's value.
Public Sub ToString As String
	Return Tjo.RunMethod("toString",Null)
End Sub
