B4J=true
Group=Default Group
ModulesStructureVersion=1
Type=StaticCode
Version=2.8
@EndOfDesignText@

Sub Process_Globals
	'Private fx As JFX ' Uncomment if required for B4j only

	'Constants / Fields are defined here
'	'The printable area's origin is at the bottom left of the paper.
'	Public LANDSCAPE As String = "LANDSCAPE"
'	'The printable area's origin is at the top left of the paper.
'	Public PORTRAIT As String = "PORTRAIT"
'	'The printable area's origin is at the top right of the paper.
'	Public REVERSE_LANDSCAPE As String = "REVERSE_LANDSCAPE"
'	'The printable area's origin is at the bottom right of the paper.
'	Public REVERSE_PORTRAIT As String = "REVERSE_PORTRAIT"
	
'	Private JOPO As JavaObject

	Private mInitialized As Boolean

End Sub
'Initializes the object. You can add parameters to this method if needed.
'If you only want to get the Values from fields, there is no longer a need to initialize this Module
Public Sub Initialize
	'This is an autogenerated constructor, there may not be a matching constructor in the class, you will then have to remove the next line of code
'	JOPO.InitializeStatic("javafx.print.PageOrientation")
'	UpdateConstants
	mInitialized = True
End Sub

'The printable area's origin is at the bottom left of the paper.
Public Sub LANDSCAPE As String
	Dim Tjo As JavaObject
	Tjo.InitializeStatic("javafx.print.PageOrientation")
	Return Tjo.GetFieldJO("LANDSCAPE").RunMethod("toString",Null)
End Sub

'The printable area's origin is at the top left of the paper.
Public Sub PORTRAIT As String
	Dim Tjo As JavaObject
	Tjo.InitializeStatic("javafx.print.PageOrientation")
	Return Tjo.GetFieldJO("PORTRAIT").RunMethod("toString",Null)
End Sub

'The printable area's origin is at the top right of the paper.
Public Sub REVERSE_LANDSCAPE As String
	Dim Tjo As JavaObject
	Tjo.InitializeStatic("javafx.print.PageOrientation")
	Return Tjo.GetFieldJO("REVERSE_LANDSCAPE").RunMethod("toString",Null)
End Sub

'The printable area's origin is at the bottom right of the paper.
Public Sub REVERSE_PORTRAIT As String
	Dim Tjo As JavaObject
	Tjo.InitializeStatic("javafx.print.PageOrientation")
	Return Tjo.GetFieldJO("REVERSE_PORTRAIT").RunMethod("toString",Null)
End Sub

'Returns the enum constant of this type with the specified name.
Public Sub ValueOf(Name As String) As String
	Dim JO As JavaObject
	JO.InitializeStatic("javafx.print.PageOrientation")
	Return 	JO.RunMethod("valueOf",Array As Object(Name))
End Sub
'Returns an array containing the constants of this enum type, in the order they are declared.
Public Sub Values As String()
	Dim JO As JavaObject
	JO.InitializeStatic("javafx.print.PageOrientation")
	Return JO.RunMethod("values",Null)
End Sub

'Private Sub UpdateConstants
'	LANDSCAPE = JOPO.RunMethod("valueOf",Array("LANDSCAPE"))
'	PORTRAIT = JOPO.RunMethod("valueOf",Array("PORTRAIT"))
'	REVERSE_LANDSCAPE = JOPO.RunMethod("valueOf",Array("REVERSE_LANDSCAPE"))
'	REVERSE_PORTRAIT = JOPO.RunMethod("valueOf",Array("REVERSE_PORTRAIT"))
'End Sub
Public Sub IsInitialized As Boolean
	Return mInitialized
End Sub