B4J=true
Group=Default Group
ModulesStructureVersion=1
Type=Class
Version=2.8
@EndOfDesignText@
'Class Module
Sub Class_Globals
	'Private fx As JFX ' Uncomment if required for B4j only
	Private PLayout As JavaObject
	Private mPaper As Paper

End Sub
'Initializes the object. You can add parameters to this method if needed.
Public Sub Initialize
	'This is an autogenerated constructor, there may not be a matching constructor in the class, you will then have to remove the next line of code
	PLayout.InitializeStatic("javafx.print.PageLayout")
End Sub

'Test of equality
Public Sub Equals(O As Object) As Boolean
	Return PLayout.RunMethod("equals",Array As Object(O))
End Sub
'Returns the bottom margin of the page layout in points.
Public Sub GetBottomMargin As Double
	Return PLayout.RunMethod("getBottomMargin",Null)
End Sub
'Returns the left margin of the page layout in points.
Public Sub GetLeftMargin As Double
	Return PLayout.RunMethod("getLeftMargin",Null)
End Sub
'Get the Page orientation
Public Sub GetPageOrientation As String
	Return PLayout.RunMethodJO("getPageOrientation",Null).RunMethod("toString",Null)
End Sub
'The paper used.
Public Sub GetPaper As Paper
	If Not(mPaper.IsInitialized) Then
		mPaper.Initialize
		mPaper.SetObject(PLayout.RunMethod("getPaper",Null))
	End If
	Return mPaper
End Sub
'Returns the height dimension of the printable area of the page, in 1/72 of an inch, taking into account the orientation.
Public Sub GetPrintableHeight As Double
	Return PLayout.RunMethod("getPrintableHeight",Null)
End Sub
'Returns the width dimension of the printable area of the page, in 1/72 of an inch points, taking into account the orientation.
Public Sub GetPrintableWidth As Double
	Return PLayout.RunMethod("getPrintableWidth",Null)
End Sub
'Returns the right margin of the page layout in points.
Public Sub GetRightMargin As Double
	Return PLayout.RunMethod("getRightMargin",Null)
End Sub
'Returns the top margin of the page layout in points.
Public Sub GetTopMargin As Double
	Return PLayout.RunMethod("getTopMargin",Null)
End Sub
'Returns a String Representation ot the object
Public Sub ToString As String
	Return PLayout.RunMethod("toString",Null)
End Sub
Public Sub GetObject As Object
	Return PLayout
End Sub
Public Sub SetObject (PL As Object)
	PLayout = PL
End Sub
