#import "iCore.h"
#import "iUI8.h"
@interface b4i_ipopupdialog : B4IClass
{
@public B4INativeObject* __no;
@public int __style_dark;
@public int __style_light;
@public int __style_extralight;
@public int __style_regular;
@public NSString* __close_without_result;
@public B4IPanelWrapper* __base;
@public B4IScrollView* __basescrollpanel;
@public int __popupcolor;
@public int __popupradius;
@public B4IBitmap* __mpopupimage;
@public NSString* __popupvideourl;
@public NSString* __mtitle;
@public NSString* __mbody;
@public NSString* __meventname;
@public B4IList* __mbuttons;
@public NSObject* __mcallback;
@public BOOL __mcancelable;
@public B4ILabelWrapper* __titlelabel;
@public B4ILabelWrapper* __bodylabel;
@public B4IFontWrapper* __buttontextfont;
@public int __mbuttontextcolor;
@public int __buttonbackcolor;
@public B4IVideoPlayer* __videoview;
@public B4IPanelWrapper* __controlcont;
@public B4IPanelWrapper* __videopanel;
@public B4IActivityIndicatorWrapper* __videoloading;
@public B4IButtonWrapper* __playbtn;
@public B4IPanelWrapper* __mcustomview;
@public int __width;
@public int __height;

}- (NSString*)  _button_click;
- (NSString*)  _class_globals;
@property (nonatomic)B4INativeObject* _no;
@property (nonatomic)int _style_dark;
@property (nonatomic)int _style_light;
@property (nonatomic)int _style_extralight;
@property (nonatomic)int _style_regular;
@property (nonatomic)NSString* _close_without_result;
@property (nonatomic)B4IPanelWrapper* _base;
@property (nonatomic)B4IScrollView* _basescrollpanel;
@property (nonatomic)int _popupcolor;
@property (nonatomic)int _popupradius;
@property (nonatomic)B4IBitmap* _mpopupimage;
@property (nonatomic)NSString* _popupvideourl;
@property (nonatomic)NSString* _mtitle;
@property (nonatomic)NSString* _mbody;
@property (nonatomic)NSString* _meventname;
@property (nonatomic)B4IList* _mbuttons;
@property (nonatomic)NSObject* _mcallback;
@property (nonatomic)BOOL _mcancelable;
@property (nonatomic)B4ILabelWrapper* _titlelabel;
@property (nonatomic)B4ILabelWrapper* _bodylabel;
@property (nonatomic)B4IFontWrapper* _buttontextfont;
@property (nonatomic)int _mbuttontextcolor;
@property (nonatomic)int _buttonbackcolor;
@property (nonatomic)B4IVideoPlayer* _videoview;
@property (nonatomic)B4IPanelWrapper* _controlcont;
@property (nonatomic)B4IPanelWrapper* _videopanel;
@property (nonatomic)B4IActivityIndicatorWrapper* _videoloading;
@property (nonatomic)B4IButtonWrapper* _playbtn;
@property (nonatomic)B4IPanelWrapper* _mcustomview;
@property (nonatomic)int _width;
@property (nonatomic)int _height;
- (void)  _close:(BOOL) _noresult;
- (NSString*)  _closepopup;
- (NSString*)  _content_click;
- (NSString*)  _controlcont_click;
- (NSString*)  _createbutton:(B4IPanelWrapper*) _p :(NSString*) _title :(BOOL) _topborder :(BOOL) _leftborder;
- (b4i_ipopupdialog*)  _initialize:(B4I*) _ba :(NSString*) _eventname :(NSObject*) _callback :(NSString*) _title :(NSString*) _body :(B4IList*) _buttons :(BOOL) _cancelable;
- (NSString*)  _overlay_click;
- (NSString*)  _playbtn_click;
- (int)  _popupwidth;
- (NSString*)  _resize;
- (NSString*)  _setbuttonbackgroundcolor:(int) _color;
- (NSString*)  _setbuttonfont:(B4IFontWrapper*) _textfont;
- (NSString*)  _setbuttontextcolor:(int) _color;
- (NSString*)  _setcustomview:(B4IPanelWrapper*) _customview;
- (NSString*)  _setpopupbackgroundcolor:(int) _color;
- (NSString*)  _setpopupcornerradius:(int) _radius;
- (NSString*)  _setpopupimage:(B4IBitmap*) _image;
- (NSString*)  _setpopupvideo:(NSString*) _url;
- (NSString*)  _setupcontent;
- (NSString*)  _show:(int) _style;
- (NSString*)  _updatepostion:(float) _newheight;
- (NSString*)  _videoview_complete;
- (NSString*)  _videoview_ready:(BOOL) _success;
@end

