B4J=true
Group=Default Group
ModulesStructureVersion=1
Type=Class
Version=9.8
@EndOfDesignText@
#Event: Click(Btn As Object)
Sub Class_Globals
	Private mCallBack As Object
	Private mEventName As String
End Sub

'Initializes the object. You can add parameters to this method if needed.
Public Sub Initialize(CallBack As Object,EventName As String)
	mCallBack = CallBack
	mEventName = EventName
	(Me).As(JavaObject).RunMethod("create",Array("Button"))
End Sub

Private Sub Button_Click(E As Object)
	'Use CallSubDelayed to remove the call from the EventDispatch thread.
	CallSubDelayed2(mCallBack,mEventName & "_Click",E.As(JavaObject).RunMethod("getSource",Null))
End Sub

#if java
//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import anywheresoftware.b4a.keywords.Common;

public class MyPanel extends JPanel {
    private JButton jcomp1;
    private JButton jcomp2;
    private JButton jcomp3;
    private JButton jcomp4;
    private JButton jcomp5;
    
           public MyPanel(String eventName) {
        //construct components
        jcomp1 = new JButton ("Print Text");
        jcomp2 = new JButton ("Dump Text");
        jcomp3 = new JButton ("Print Image Pj");
        jcomp4 = new JButton ("Print Image Dpj");
        jcomp5 = new JButton ("Print Book");
       
		
		ActionListener al = new ActionListener() {
			public void actionPerformed(ActionEvent e){
				ba.raiseEvent(this, eventName.toLowerCase(BA.cul) + "_click",e);
			}
		};
		
		jcomp1.addActionListener(al);
		jcomp2.addActionListener(al);
		jcomp3.addActionListener(al);
		jcomp4.addActionListener(al);
		jcomp5.addActionListener(al);
		
        //adjust size and set layout
        setPreferredSize (new Dimension (257, 123));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
       

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (0, 0, 125, 20);
        jcomp2.setBounds (130, 0, 125, 20);
        jcomp3.setBounds (0, 20, 125, 20);
        jcomp4.setBounds (130, 20, 125, 25);
        jcomp5.setBounds (-5, 40, 130, 25);
    }

}

    public void create (String eventName) {
        JFrame frame = new JFrame ("Gui");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MyPanel(eventName));
        frame.pack();
		frame.setLocationRelativeTo(null);
        frame.setVisible (true);
    }
#End If