B4A=true
Group=Default Group
ModulesStructureVersion=1
Type=StaticCode
Version=13.4
@EndOfDesignText@
#ModuleVisibility: B4XLib
'Code module
'Subs in this code module will be accessible from all modules.
Sub Process_Globals
	'These global variables will be declared once when the application starts.
	'These variables can be accessed from all modules.
End Sub

Public Sub PolicyInapp As String
	Return $"<!DOCTYPE html>
	<html>
	<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<title>Privacy Policy</title>
	<style>
	body {
	font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
	padding: 1em;
	background-color: #1a1a1f;
	color: #e4e4e8;
	line-height: 1.6;
	}
	strong {
	color: #ffffff;
	}
	a {
	color: #b48cff;
	text-decoration: none;
	}
	a:hover {
	text-decoration: underline;
	}
	</style>
	</head>
	
	<body>

	<strong>Privacy Policy</strong>

	<p>
	[COMPANY_NAME] provides the <strong>[APP_NAME]</strong> Application ("Service").
	</p>

	<p>
	This page describes our policies regarding information collection, use, And disclosure in connection with the Service.
	</p>

	<p><strong>Information Collection And Use</strong></p>

	<p>
	The Service does Not require user accounts And does Not intentionally collect personally identifiable information.
	</p>

	<p>
	No names, email addresses, contact details, account credentials, Or identifying information are collected Or stored by [COMPANY_NAME] through the Service.
	</p>

	<p><strong>In-App Purchases</strong></p>

	<p>
	The Service may offer optional paid features Or content.
	Payments are processed by the applicable platform provider.
	[COMPANY_NAME] does Not receive Or store payment card details Or billing information.
	</p>

	<p><strong>Log Data</strong></p>

	<p>
	The Service does Not intentionally collect diagnostic Or usage data.
	Any technical data generated by the device, operating system, Or distribution platform Is governed by their respective privacy policies.
	</p>

	<p><strong>Cookies And Tracking Technologies</strong></p>

	<p>
	The Service does Not use cookies Or similar tracking technologies.
	</p>

	<p><strong>Third-Party Services</strong></p>

	<p>
	The Service may contain links Or references To third-party services.
	These services operate independently And have their own privacy policies.
	We recommend reviewing those policies before providing any information.
	</p>

	<p><strong>Children’s Privacy</strong></p>

	<p>
	The Service Is Not intended To knowingly collect personal information from children.
	If you believe that personal information has been provided through the Service, please contact us so appropriate action can be taken.
	</p>

	<p><strong>Changes To This Privacy Policy</strong></p>

	<p>
	This Privacy Policy may be updated periodically.
	Updates will be reflected on this page with a revised effective date.
	</p>

	<p>
	This policy Is effective As of <strong>[EFFECTIVE_DATE]</strong>.
	</p>

	<p><strong>Contact Us</strong></p>

	<p>
	If you have questions regarding this Privacy Policy, please contact:
	<a href="mailto:[CONTACT_EMAIL]">[CONTACT_EMAIL]</a>.
	</p>

	</body>
	</html>
	"$
End Sub

Public Sub PolicySubscription As String
	Return $"<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>Privacy Policy</title>
<style>
  body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    padding: 1em;
    background-color: #1a1a1f;
    color: #e4e4e8;
    line-height: 1.6;
  }

  strong {
    color: #ffffff;
  }

  a {
    color: #b48cff;
    text-decoration: none;
  }

  a:hover {
    text-decoration: underline;
  }

  ul {
    padding-left: 1.2em;
  }

  li {
    margin-bottom: 0.4em;
  }

  p {
    max-width: 900px;
  }
</style>
</head>
<body>

<strong>Privacy Policy</strong>

<p>
[COMPANY_NAME] provides the <strong>[APP_NAME]</strong> application ("Service").
This Service offers optional paid subscriptions to unlock additional features.
</p>

<p>
This page explains how information is handled when you use the Service.
</p>

<p><strong>Information Collection and Use</strong></p>

<p>
The Service does not require user accounts and does not collect personally identifiable
information such as names, email addresses, or contact details.
</p>

<p>
Core app functionality operates without collecting personal data.
</p>

<p><strong>Crash and Diagnostic Data</strong></p>

<p>
In the event of an application error, limited technical diagnostic information may be
collected to help identify and fix stability issues.
</p>

<p>
This information may include device type, operating system version,
app version, and technical error details. This data does not include personal identifiers.
</p>

<p>
Crash reporting data is used solely to improve reliability and performance of the Service.
</p>

<p><strong>Subscriptions and Payments</strong></p>

<p>
Subscriptions are processed by the platform through which the app is distributed.
[COMPANY_NAME] does not receive or store payment card details or billing information.
</p>

<p><strong>Data Storage</strong></p>

<p>
App data is primarily stored locally on your device. You may remove locally stored
data at any time by uninstalling the app.
</p>

<p><strong>Security</strong></p>

<p>
Reasonable measures are taken to protect data handled by the Service.
However, no electronic transmission or storage method is completely secure.
</p>

<p><strong>Children’s Privacy</strong></p>

<p>
The Service is not intended to knowingly collect personal information from children.
If you believe information has been provided by a child, please contact us.
</p>

<p><strong>Changes to This Privacy Policy</strong></p>

<p>
This Privacy Policy may be updated periodically.
Updates will be posted on this page with a revised effective date.
</p>

<p>
This policy is effective as of <strong>[EFFECTIVE_DATE]</strong>.
</p>

<p><strong>Contact Us</strong></p>

<p>
If you have any questions regarding this Privacy Policy, please contact:
<a href="mailto:[CONTACT_EMAIL]">[CONTACT_EMAIL]</a>.
</p>

</body>
</html>
"$
End Sub

Public Sub PolicyToS As String
	Return $"<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>Terms of Service</title>
<style>
  body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    padding: 1em;
    background-color: #1a1a1f;
    color: #e4e4e8;
    line-height: 1.6;
  }

  strong {
    color: #ffffff;
  }

  a {
    color: #b48cff;
    text-decoration: none;
  }

  a:hover {
    text-decoration: underline;
  }

  ul {
    padding-left: 1.2em;
  }

  li {
    margin-bottom: 0.4em;
  }

  p {
    max-width: 900px;
  }
</style>
</head>
<body>

<strong>Terms of Service</strong>

<p>
By downloading, installing, or using the <strong>[APP_NAME]</strong> application ("Service"),
you agree to these Terms of Service ("Terms"). If you do not agree, do not use the Service.
</p>

<p><strong>Use of the Service</strong></p>

<p>
You agree to use the Service only for lawful purposes and in accordance with these Terms.
You are responsible for maintaining the security of your device and your access to the Service.
</p>

<p><strong>License and Restrictions</strong></p>

<p>
[COMPANY_NAME] grants you a limited, non-exclusive, non-transferable, revocable license
to use the Service for personal use, subject to these Terms.
</p>

<p>
You may not copy, modify, distribute, sell, lease, reverse engineer, decompile,
or attempt to extract the source code of the Service, except where such restriction is prohibited by law.
</p>

<p><strong>Intellectual Property</strong></p>

<p>
All rights, title, and interest in and to the Service (including branding, design, content,
and any related intellectual property) remain the property of [COMPANY_NAME] or its licensors.
</p>

<p><strong>Subscriptions and Purchases</strong></p>

<p>
The Service may offer paid subscriptions or other purchases to unlock additional features or content.
Prices and subscription terms are displayed at the time of purchase.
</p>

<p>
Subscriptions renew automatically unless canceled before the end of the current billing period.
You can manage or cancel subscriptions through the platform or account used to purchase the subscription.
</p>

<p>
If a free trial is offered, any unused portion of the trial may be forfeited when a paid subscription begins,
as permitted by the applicable purchase terms.
</p>

<p><strong>Changes to the Service and Pricing</strong></p>

<p>
[COMPANY_NAME] may update, modify, suspend, or discontinue any part of the Service at any time.
Pricing and available features may change, and any paid changes will be disclosed before purchase.
</p>

<p><strong>Internet and Availability</strong></p>

<p>
Some features may require an active internet connection. The Service may be unavailable from time to time
due to maintenance, connectivity issues, or factors outside of [COMPANY_NAME]'s control.
</p>

<p><strong>Disclaimer</strong></p>

<p>
The Service is provided "as is" and "as available" without warranties of any kind, express or implied.
To the maximum extent permitted by law, [COMPANY_NAME] disclaims all warranties including fitness
for a particular purpose, non-infringement, and uninterrupted availability.
</p>

<p><strong>Limitation of Liability</strong></p>

<p>
To the maximum extent permitted by law, [COMPANY_NAME] is not liable for any indirect, incidental,
special, consequential, or punitive damages, or any loss of data, profits, or business opportunities,
arising from or related to your use of (or inability to use) the Service.
</p>

<p><strong>Termination</strong></p>

<p>
[COMPANY_NAME] may terminate or suspend access to the Service at any time if you violate these Terms.
Upon termination, you must stop using the Service and remove it from your device.
</p>

<p><strong>Changes to These Terms</strong></p>

<p>
These Terms may be updated periodically. Continued use of the Service after updates are posted
means you accept the revised Terms.
</p>

<p>
These Terms are effective as of <strong>[EFFECTIVE_DATE]</strong>.
</p>

<p><strong>Contact Us</strong></p>

<p>
If you have questions about these Terms, contact:
<a href="mailto:[CONTACT_EMAIL]">[CONTACT_EMAIL]</a>.
</p>

</body>
</html>
"$
End Sub

'************ Purchase screen templates ******************
Public Sub PurchaseInapp As String
	Return $"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>[APP_NAME]</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            -webkit-tap-highlight-color: transparent;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background-color: [COLOR_BG1];
            color: [TEXT_COLOR];
            /* Safe area for notches and nav buttons */
            padding: env(safe-area-inset-top, 0) env(safe-area-inset-right, 0) env(safe-area-inset-bottom, 0) env(safe-area-inset-left, 0);
        }

        /* Content container */
        .container {
            padding: clamp(1.5rem, 3vh, 2rem) clamp(1rem, 4vw, 1.5rem);
            padding-bottom: clamp(1rem, 2vh, 1.5rem);
        }

        /* Header */
        .header {
            text-align: center;
            margin-bottom: clamp(1.5rem, 3vh, 2rem);
            animation: fadeInDown 0.8s ease-out;
        }

        .logo {
            font-size: clamp(1.7rem, 6.5vw, 2.5rem);
            font-weight: 700;
            background: linear-gradient(135deg, [COLOR_PRIMARY] 0%, [COLOR_SECONDARY] 50%, [COLOR_ACCENT] 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            margin-bottom: 0.3rem;
            letter-spacing: 0.1em;
            text-shadow: 0 0 30px rgba(0, 255, 255, 0.3);
        }

        .tagline {
            font-size: clamp(0.8rem, 2.3vw, 0.95rem);
            color: [TEXT_COLOR_ALPHA];
            font-weight: 300;
            letter-spacing: 0.05em;
        }

        /* Features section */
        .features {
            display: flex;
            flex-direction: column;
            gap: clamp(0.6rem, 1.5vh, 0.9rem);
            margin-bottom: clamp(1.5rem, 3vh, 2rem);
            animation: fadeIn 1s ease-out 0.3s both;
        }
        
        /* Hide features container if empty */
        .features:empty {
            display: none;
        }

        .feature {
            display: flex;
            align-items: center;
            gap: clamp(0.7rem, 2vw, 1rem);
            padding: clamp(0.6rem, 2vh, 0.9rem);
            background: [FEATURE_BG];
            border: 1px solid [FEATURE_BORDER];
            border-radius: 0.7rem;
            backdrop-filter: blur(10px);
            transition: all 0.3s ease;
        }

        .feature:hover {
            background: [FEATURE_HOVER_BG];
            border-color: rgba(0, 122, 255, 0.3);
            transform: translateX(5px);
        }

        .feature-icon {
            width: clamp(2rem, 7vw, 2.5rem);
            height: clamp(2rem, 7vw, 2.5rem);
            border-radius: 50%;
            background: linear-gradient(135deg, [COLOR_PRIMARY_ALPHA], [COLOR_SECONDARY_ALPHA]);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: clamp(1.4rem, 5vw, 1.8rem);
            flex-shrink: 0;
        }

        .feature-text h3 {
            font-size: clamp(0.95rem, 3.5vw, 1.2rem);
            margin-bottom: 0.2rem;
            font-weight: 600;
        }

        .feature-text p {
            font-size: clamp(0.8rem, 2.8vw, 0.95rem);
            color: [TEXT_COLOR_ALPHA];
            line-height: 1.3;
        }

        /* Purchase section */
        .purchase-section {
            animation: fadeInUp 0.8s ease-out 0.5s both;
        }

        /* Products - no scrollable container, just natural flow */
        .products-list {
            margin-bottom: clamp(1.5rem, 3vh, 2rem);
        }

        .product-card {
            background: [FEATURE_BG];
            border: 1px solid [FEATURE_BORDER];
            border-radius: 0.9rem;
            padding: clamp(1rem, 2.5vh, 1.3rem);
            margin-bottom: clamp(0.8rem, 2vh, 1rem);
            transition: all 0.3s ease;
        }

        .product-card:last-child {
            margin-bottom: 0;
        }

        .product-card:hover {
            background: [FEATURE_HOVER_BG];
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        }

        .product-header {
            margin-bottom: 0.8rem;
        }

        .product-title {
            font-size: clamp(1.1rem, 4vw, 1.4rem);
            font-weight: 600;
            color: [TEXT_COLOR];
            margin-bottom: 0.3rem;
        }

        .product-description {
            font-size: clamp(0.85rem, 2.8vw, 0.95rem);
            color: [TEXT_COLOR_ALPHA];
            line-height: 1.4;
        }

        .product-footer {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 1rem;
        }

        .product-price {
            font-size: clamp(1.5rem, 5vw, 2rem);
            font-weight: 700;
            color: [TEXT_COLOR];
        }

        .btn-buy {
            padding: clamp(0.7rem, 2.5vh, 0.9rem) clamp(1.5rem, 5vw, 2rem);
            font-size: clamp(0.9rem, 3vw, 1rem);
            font-weight: 600;
            color: [BUTTON_TEXT_COLOR];
            background: linear-gradient(135deg, [COLOR_PRIMARY] 0%, [COLOR_SECONDARY] 100%);
            border: none;
            border-radius: 0.7rem;
            cursor: pointer;
            transition: all 0.3s ease;
            box-shadow: 0 2px 8px rgba(0, 122, 255, 0.3);
            letter-spacing: 0.03em;
            text-transform: uppercase;
            white-space: nowrap;
        }

        .btn-buy:active {
            transform: scale(0.98);
            box-shadow: 0 1px 4px rgba(0, 122, 255, 0.4);
        }

        /* Buttons container with divider */
        .buttons-container {
            padding-top: clamp(1rem, 2.5vh, 1.5rem);
            border-top: 1px solid [DIVIDER_COLOR];
        }

        .btn-restore {
            width: 100%;
            padding: clamp(0.7rem, 2.5vh, 0.9rem);
            font-size: clamp(0.9rem, 3vw, 1rem);
            font-weight: 500;
            color: rgba(0, 122, 255, 1);
            background: transparent;
            border: 1px solid rgba(0, 122, 255, 0.5);
            border-radius: 0.7rem;
            cursor: pointer;
            transition: all 0.3s ease;
            margin-bottom: clamp(0.9rem, 2vh, 1.3rem);
        }

        .btn-restore:active {
            background: rgba(0, 122, 255, 0.1);
            border-color: rgba(0, 122, 255, 0.8);
            transform: scale(0.98);
        }

        .btn-close {
            width: 100%;
            padding: clamp(0.7rem, 2.5vh, 0.9rem);
            font-size: clamp(0.9rem, 3vw, 1rem);
            font-weight: 500;
            color: rgba(0, 122, 255, 1);
            background: transparent;
            border: none;
            cursor: pointer;
            transition: all 0.3s ease;
            margin-bottom: 0;
            text-decoration: none;
            letter-spacing: 0.02em;
        }

        .btn-close:active {
            color: rgba(0, 122, 255, 0.7);
        }

        /* Animations */
        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }

        @keyframes fadeInDown {
            from {
                opacity: 0;
                transform: translateY(-20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        @keyframes fadeOut {
            from {
                opacity: 1;
                transform: scale(1);
            }
            to {
                opacity: 0;
                transform: scale(0.95);
            }
        }

        /* Closing state */
        .closing {
            animation: fadeOut 0.3s ease-out forwards;
        }

        /* Loading state */
        .loading {
            pointer-events: none;
            opacity: 0.6;
        }

        .loading .btn-purchase::after {
            content: '';
            display: inline-block;
            width: 1rem;
            height: 1rem;
            margin-left: 0.5rem;
            border: 2px solid #FFFFFF;
            border-top-color: transparent;
            border-radius: 50%;
            animation: spin 0.6s linear infinite;
        }

        @keyframes spin {
            to { transform: rotate(360deg); }
        }

        /* Processing overlay - blocks entire screen */
        .processing-overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: [OVERLAY_BG];
            backdrop-filter: blur(8px);
            display: none;
            align-items: center;
            justify-content: center;
            z-index: 1000;
            animation: fadeIn 0.3s ease-out;
        }

        .processing-overlay.active {
            display: flex;
        }

        .processing-content {
            text-align: center;
            animation: fadeInUp 0.5s ease-out;
        }

        .processing-spinner {
            width: 3rem;
            height: 3rem;
            border: 3px solid [COLOR_PRIMARY_ALPHA];
            border-top-color: [COLOR_PRIMARY];
            border-radius: 50%;
            animation: spin 0.8s linear infinite;
            margin: 0 auto 1rem;
        }

        .processing-text {
            font-size: 1.1rem;
            color: [TEXT_COLOR];
            font-weight: 500;
            letter-spacing: 0.05em;
        }
    </style>
</head>
<body>
    <!-- Processing overlay -->
    <div class="processing-overlay" id="processingOverlay">
        <div class="processing-content">
            <div class="processing-spinner"></div>
            <div class="processing-text" id="processingText">Processing...</div>
        </div>
    </div>

    <!-- Main content -->
    <div class="container">
        <!-- Header -->
        <div class="header">
            <div class="logo">[APP_NAME]</div>
            <div class="tagline">[APP_TAGLINE]</div>
        </div>

        <!-- Features -->
        <div class="features">[FEATURES]</div>

        <!-- Purchase section -->
        <div class="purchase-section">
            <div class="products-list">
                [PRODUCTS]
            </div>

            <div class="buttons-container">
                <button class="btn-restore" id="btnRestore" onclick="restore()">
                    Restore Purchase
                </button>

                <button class="btn-close" onclick="closeScreen()">
                    Maybe Later
                </button>
            </div>
        </div>
    </div>

    <script>
        // B4X communication functions
        function purchase(productId) {
            // Show processing overlay
            showProcessing('Processing purchase...');
            
            // Call B4X with product ID
            window.location = 'b4x://purchase?product=' + encodeURIComponent(productId);
        }

        function restore() {
            // Show processing overlay
            showProcessing('Restoring purchases...');
            
            // Call B4X
            window.location = 'b4x://restore';
        }

        function closeScreen() {
            console.log('🔴 Close button clicked');
            
            // Add closing animation
            document.body.classList.add('closing');
            
            // Wait for animation to complete, then call B4X
            setTimeout(() => {
                console.log('🔴 Calling b4x://close');
                window.location = 'b4x://close';
            }, 300);
        }

        // Show processing overlay
        function showProcessing(message) {
            const overlay = document.getElementById('processingOverlay');
            const text = document.getElementById('processingText');
            text.textContent = message;
            overlay.classList.add('active');
        }

        // Hide processing overlay
        function hideProcessing() {
            const overlay = document.getElementById('processingOverlay');
            overlay.classList.remove('active');
        }

        // Update price from B4X (deprecated - use updateProductPrice)
        function setPrice(price) {
            // Deprecated - kept for backward compatibility
        }

        // Update product price dynamically
        function updateProductPrice(productId, price) {
            const priceElement = document.getElementById('price-' + productId);
            if (priceElement) {
                priceElement.textContent = price;
            }
        }

        // Reset button states (called from B4X after operation completes)
        function resetButtons() {
            hideProcessing();
        }
    </script>
</body>
</html>
"$
End Sub

Public Sub PurchaseSubscription As String
	Return $"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>[APP_NAME]</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            -webkit-tap-highlight-color: transparent;
        }

        html {
            height: 100%;
            overflow: hidden;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, [COLOR_BG1] 0%, [COLOR_BG2] 100%);
            color: [TEXT_COLOR];
            height: 100%;
            overflow: hidden;
            display: flex;
            flex-direction: column;
            /* Safe area for notches and nav buttons */
            padding: env(safe-area-inset-top, 0) env(safe-area-inset-right, 0) env(safe-area-inset-bottom, 0) env(safe-area-inset-left, 0);
        }

        /* Scrollable content wrapper */
        .scroll-wrapper {
            flex: 1;
            overflow-y: auto;
            overflow-x: hidden;
            -webkit-overflow-scrolling: touch;
        }

        /* Content container */
        .container {
            padding: clamp(1.5rem, 3vh, 2rem) clamp(1rem, 4vw, 1.5rem);
            /* Add padding for fixed footer at bottom (footer height ~10rem) */
            padding-bottom: calc(10rem + env(safe-area-inset-bottom, 0));
        }

        /* Header */
        .header {
            text-align: center;
            margin-bottom: clamp(1.5rem, 3vh, 2rem);
            animation: fadeInDown 0.8s ease-out;
        }

        .logo {
            font-size: clamp(1.7rem, 6.5vw, 2.5rem);
            font-weight: 700;
            background: linear-gradient(135deg, [COLOR_PRIMARY] 0%, [COLOR_SECONDARY] 50%, [COLOR_ACCENT] 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            margin-bottom: 0.3rem;
            letter-spacing: 0.1em;
            text-shadow: 0 0 30px rgba(0, 255, 255, 0.3);
        }

        .tagline {
            font-size: clamp(0.8rem, 2.3vw, 0.95rem);
            color: [TEXT_COLOR_ALPHA];
            font-weight: 300;
            letter-spacing: 0.05em;
        }

        /* Features section */
        .features {
            display: flex;
            flex-direction: column;
            gap: clamp(0.6rem, 1.5vh, 0.9rem);
            margin-bottom: clamp(1.5rem, 3vh, 2rem);
            animation: fadeIn 1s ease-out 0.3s both;
        }

        .feature {
            display: flex;
            align-items: center;
            gap: clamp(0.7rem, 2vw, 1rem);
            padding: clamp(0.6rem, 2vh, 0.9rem);
            background: [FEATURE_BG];
            border: 1px solid [FEATURE_BORDER];
            border-radius: 0.7rem;
            backdrop-filter: blur(10px);
            transition: all 0.3s ease;
        }

        .feature:hover {
            background: [FEATURE_HOVER_BG];
            border-color: rgba(0, 122, 255, 0.3);
            transform: translateX(5px);
        }

        .feature-icon {
            width: clamp(2rem, 7vw, 2.5rem);
            height: clamp(2rem, 7vw, 2.5rem);
            border-radius: 50%;
            background: linear-gradient(135deg, [COLOR_PRIMARY_ALPHA], [COLOR_SECONDARY_ALPHA]);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: clamp(1.4rem, 5vw, 1.8rem);
            flex-shrink: 0;
        }

        .feature-text h3 {
            font-size: clamp(0.95rem, 3.5vw, 1.2rem);
            margin-bottom: 0.2rem;
            font-weight: 600;
        }

        .feature-text p {
            font-size: clamp(0.8rem, 2.8vw, 0.95rem);
            color: [TEXT_COLOR_ALPHA];
            line-height: 1.3;
        }

        /* Purchase section */
        .purchase-section {
            animation: fadeInUp 0.8s ease-out 0.5s both;
        }

        /* Products - no scrollable container, just natural flow */
        .products-list {
            margin-bottom: clamp(1.5rem, 3vh, 2rem);
        }

        /* Action buttons that scroll with content */
        .action-buttons {
            padding-top: clamp(1rem, 2.5vh, 1.5rem);
            border-top: 1px solid [DIVIDER_COLOR];
            margin-bottom: clamp(1.5rem, 3vh, 2rem);
        }

        .product-card {
            background: [FEATURE_BG];
            border: 1px solid [FEATURE_BORDER];
            border-radius: 0.9rem;
            padding: clamp(1rem, 2.5vh, 1.3rem);
            margin-bottom: clamp(0.8rem, 2vh, 1rem);
            transition: all 0.3s ease;
        }

        .product-card:last-child {
            margin-bottom: 0;
        }

        .product-card:hover {
            background: [FEATURE_HOVER_BG];
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        }

        .product-header {
            margin-bottom: 0.8rem;
        }

        .product-title {
            font-size: clamp(1.1rem, 4vw, 1.4rem);
            font-weight: 600;
            color: [TEXT_COLOR];
            margin-bottom: 0.3rem;
        }

        .product-description {
            font-size: clamp(0.85rem, 2.8vw, 0.95rem);
            color: [TEXT_COLOR_ALPHA];
            line-height: 1.4;
        }

        .product-footer {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 1rem;
        }

        .product-price {
            font-size: clamp(1.5rem, 5vw, 2rem);
            font-weight: 700;
            color: [TEXT_COLOR];
        }

        .btn-buy {
            padding: clamp(0.7rem, 2.5vh, 0.9rem) clamp(1.5rem, 5vw, 2rem);
            font-size: clamp(0.9rem, 3vw, 1rem);
            font-weight: 600;
            color: [BUTTON_TEXT_COLOR];
            background: linear-gradient(135deg, [COLOR_PRIMARY] 0%, [COLOR_SECONDARY] 100%);
            border: none;
            border-radius: 0.7rem;
            cursor: pointer;
            transition: all 0.3s ease;
            box-shadow: 0 2px 8px rgba(0, 122, 255, 0.3);
            letter-spacing: 0.03em;
            text-transform: uppercase;
            white-space: nowrap;
        }

        .btn-buy:active {
            transform: scale(0.98);
            box-shadow: 0 1px 4px rgba(0, 122, 255, 0.4);
        }

        /* Buttons container with divider - STICKY FOOTER (fixed position) */
        .legal-footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            background: rgba(0,0,0,0.3);
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
            padding: clamp(0.8rem, 2vh, 1rem) clamp(1rem, 4vw, 1.5rem);
            padding-bottom: clamp(0.8rem, 2vh, 1rem);
            border-top: 1px solid rgba(255,255,255,0.1);
            z-index: 1000;
        }

        .btn-restore {
            width: 100%;
            padding: clamp(0.7rem, 2.5vh, 0.9rem);
            font-size: clamp(0.9rem, 3vw, 1rem);
            font-weight: 500;
            color: [COLOR_PRIMARY];
            background: transparent;
            border: 1px solid [COLOR_PRIMARY_ALPHA];
            border-radius: 0.7rem;
            cursor: pointer;
            transition: all 0.3s ease;
            margin-bottom: clamp(0.7rem, 1.5vh, 0.9rem);
        }

        .btn-restore:active {
            background: [COLOR_PRIMARY_ALPHA];
            border-color: [COLOR_PRIMARY];
            transform: scale(0.98);
        }

        .btn-close {
            width: 100%;
            padding: clamp(0.7rem, 2.5vh, 0.9rem);
            font-size: clamp(0.9rem, 3vw, 1rem);
            font-weight: 500;
            color: [COLOR_PRIMARY];
            background: transparent;
            border: none;
            cursor: pointer;
            transition: all 0.3s ease;
            margin-bottom: 0;
            text-decoration: none;
            letter-spacing: 0.02em;
        }

        .btn-close:active {
            color: [COLOR_SECONDARY];
        }

        /* Legal links */
        .legal-links {
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 0.8rem;
            margin-bottom: clamp(0.5rem, 1vh, 0.7rem);
            font-size: clamp(0.9rem, 3.2vw, 1rem);
        }

        .legal-links a {
            color: rgba(0, 122, 255, 1);
            text-decoration: none;
            opacity: 1;
            transition: all 0.3s ease;
            letter-spacing: 0.02em;
            font-weight: 500;
        }

        .legal-links a:active {
            opacity: 0.7;
            transform: scale(0.98);
        }

        .legal-separator {
            color: rgba(0, 122, 255, 0.5);
            opacity: 1;
            font-size: 0.85rem;
        }

        /* Subscription info */
        .subscription-info {
            text-align: center;
            font-size: clamp(0.75rem, 2.5vw, 0.85rem);
            color: [TEXT_COLOR_ALPHA];
            opacity: 0.7;
            line-height: 1.5;
            padding: 0 clamp(0.5rem, 2vw, 1rem);
            margin: 0;
        }

        /* Animations */
        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }

        @keyframes fadeInDown {
            from {
                opacity: 0;
                transform: translateY(-20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        @keyframes fadeOut {
            from {
                opacity: 1;
                transform: scale(1);
            }
            to {
                opacity: 0;
                transform: scale(0.95);
            }
        }

        /* Closing state */
        .closing {
            animation: fadeOut 0.3s ease-out forwards;
        }

        /* Loading state */
        .loading {
            pointer-events: none;
            opacity: 0.6;
        }

        .loading .btn-purchase::after {
            content: '';
            display: inline-block;
            width: 1rem;
            height: 1rem;
            margin-left: 0.5rem;
            border: 2px solid #FFFFFF;
            border-top-color: transparent;
            border-radius: 50%;
            animation: spin 0.6s linear infinite;
        }

        @keyframes spin {
            to { transform: rotate(360deg); }
        }

        /* Processing overlay - blocks entire screen */
        .processing-overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: [OVERLAY_BG];
            backdrop-filter: blur(8px);
            display: none;
            align-items: center;
            justify-content: center;
            z-index: 1000;
            animation: fadeIn 0.3s ease-out;
        }

        .processing-overlay.active {
            display: flex;
        }

        .processing-content {
            text-align: center;
            animation: fadeInUp 0.5s ease-out;
        }

        .processing-spinner {
            width: 3rem;
            height: 3rem;
            border: 3px solid [COLOR_PRIMARY_ALPHA];
            border-top-color: [COLOR_PRIMARY];
            border-radius: 50%;
            animation: spin 0.8s linear infinite;
            margin: 0 auto 1rem;
        }

        .processing-text {
            font-size: 1.1rem;
            color: [TEXT_COLOR];
            font-weight: 500;
            letter-spacing: 0.05em;
        }
    </style>
</head>
<body>
    <!-- Processing overlay -->
    <div class="processing-overlay" id="processingOverlay">
        <div class="processing-content">
            <div class="processing-spinner"></div>
            <div class="processing-text" id="processingText">Processing...</div>
        </div>
    </div>

    <!-- Main content (no wrapper - body scrolls directly) -->
    <div class="container">
        <!-- Header -->
        <div class="header">
            <div class="logo">[APP_NAME]</div>
            <div class="tagline">[APP_TAGLINE]</div>
        </div>

        <!-- Features -->
        <div class="features">
            [FEATURES]
        </div>

        <!-- Purchase section -->
        <div class="purchase-section">
            <div class="products-list">
                [PRODUCTS]
            </div>

            <!-- Buttons that scroll with content -->
            <div class="action-buttons">
                <button class="btn-restore" id="btnRestore" onclick="restore()">
                    Restore Purchase
                </button>

                <button class="btn-close" onclick="closeScreen()">
                    Maybe Later
                </button>
            </div>
        </div>
    </div>

    <!-- Fixed footer with legal links only -->
    <div class="legal-footer">
        <!-- Legal links -->
        <div class="legal-links">
            <a href="#" onclick="openTerms(); return false;">Terms of Service</a>
            <span class="legal-separator">•</span>
            <a href="#" onclick="openPrivacy(); return false;">Privacy Policy</a>
        </div>

        <!-- Subscription info -->
        <div class="subscription-info">
            Subscription automatically renews unless auto-renew is turned off at least 24 hours before the end of the current period.
        </div>
    </div>

    <script>
        // B4X communication functions
        function purchase(productId, basePlanId) {
            // Show processing overlay
            showProcessing('Processing subscription...');
            
            // Call B4X with product ID and base plan ID
            window.location = 'b4x://purchase?product=' + encodeURIComponent(productId) + '&plan=' + encodeURIComponent(basePlanId);
        }

        function restore() {
            // Show processing overlay
            showProcessing('Restoring purchases...');
            
            // Call B4X
            window.location = 'b4x://restore';
        }

        function closeScreen() {
            console.log('🔴 Close button clicked');
            
            // Add closing animation
            document.body.classList.add('closing');
            
            // Wait for animation to complete, then call B4X
            setTimeout(() => {
                console.log('🔴 Calling b4x://close');
                window.location = 'b4x://close';
            }, 300);
        }

        // Open Terms of Service
        function openTerms() {
            console.log('📄 Opening Terms of Service');
            window.location = 'b4x://terms';
        }

        // Open Privacy Policy
        function openPrivacy() {
            console.log('📄 Opening Privacy Policy');
            window.location = 'b4x://privacy';
        }

        // Show processing overlay
        function showProcessing(message) {
            const overlay = document.getElementById('processingOverlay');
            const text = document.getElementById('processingText');
            text.textContent = message;
            overlay.classList.add('active');
        }

        // Hide processing overlay
        function hideProcessing() {
            const overlay = document.getElementById('processingOverlay');
            overlay.classList.remove('active');
        }

        // Update price from B4X (deprecated - use updateProductPrice)
        function setPrice(price) {
            // Deprecated - kept for backward compatibility
        }

        // Update product price dynamically
        function updateProductPrice(productId, price) {
            const priceElement = document.getElementById('price-' + productId);
            if (priceElement) {
                priceElement.textContent = price;
            }
        }

        // Reset button states (called from B4X after operation completes)
        function resetButtons() {
            hideProcessing();
        }
    </script>
</body>
</html>
"$
End Sub